version: "3.3"
services:

  metaverse01: 
    image: "metaverse"
    ports:
      - "5252:5252"
      - "8830:8830"
      - "8831:8831"

  metaverse02:
    image: "metaverse"
    ports:
        - "5252:5252"
        - "8832:8832"
        - "8833:8833"

  metaverse03:
    image: "metaverse"
    ports:
        - "5252:5252"
        - "8834:8834"
        - "8835:8835"
         
