version: "3.3"
services:
  bootnode:
    build: .
    container_name: bootnode
    image: metaverse-pow:ver1
    user: root
    volumes:
        - "/tmp:/tmp"
    ports:
        - "9333:9933"
    networks:
        pow-net:
          ipv4_address: 172.100.0.10
    command: "--name bootnode --validator --rpc-cors all --base-path /tmp/bootnode --node-key 0000000000000000000000000000000000000000000000000000000000000111"
  node-01:
    build: .
    container_name: node01
    image: metaverse-pow:ver1
    user: root
    volumes:
        - "/tmp:/tmp"
    ports:
        - "9334:9933"
    networks:
        pow-net:
          ipv4_address: 172.100.0.20
    command: "--name node01 --validator --rpc-cors all --base-path /tmp/node01 --bootnodes /ip4/172.100.0.10/tcp/30333/p2p/12D3KooWRBaMZHnFYtT1B143sSLHkx8G6ysPSg8PMzqXkymm38Ld"
    depends_on: 
        - bootnode
  node-02:
    build: .
    container_name: node02
    image: metaverse-pow:ver1
    user: root
    volumes:
        - "/tmp:/tmp"
    ports:
        - "9335:9933"
    networks:
        pow-net:
          ipv4_address: 172.100.0.30
    depends_on: 
        - bootnode
    command: "--name node02 --validator --rpc-cors all --base-path /tmp/node02 --bootnodes /ip4/172.100.0.10/tcp/30333/p2p/12D3KooWRBaMZHnFYtT1B143sSLHkx8G6ysPSg8PMzqXkymm38Ld"

networks:
    pow-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.100.0.0/16
