version: "3.3"
services:
  rpc-01:
    image: metaversevm
    user: root
    networks:
        metaverse:
          ipv4_address: 172.30.0.10
    # ports:
    #   - "9615:9615"
    #   - "9933:9933"
    #   - "9944:9944"
    entrypoint: ["/usr/local/bin/metaversevm", "--dev", "--rpc-cors=all", "--rpc-methods=safe", "--ws-external", "--unsafe-rpc-external", "--prometheus-external", "--telemetry-url", "wss://telemetry.mvs.org/ws/submit 0", "--name", "regular-X"]
  vm:
    image: metaversevm
    user: root
    networks:
        metaverse:
          ipv4_address: 172.30.0.20
    # ports:
    #   - "9615:9615"
    #   - "9933:9933"
    #   - "9944:9944"
    #   - "30333:30333"
    entrypoint: ["/usr/local/bin/metaversevm", "--dev", "--base-path=/tmp/chaindata", "--telemetry-url", "wss://telemetry.mvs.org/ws/submit 0", "--name", "validator-X", "--validator"]
  rpc-archive-01:
    image: metaversevm
    user: root
    networks:
        metaverse:
          ipv4_address: 172.30.0.30
    # ports:
    #   - "18835:9933"
    #   - "18845:9944"
    entrypoint: ["/usr/local/bin/metaversevm", "--dev", "--rpc-cors=all", "--rpc-methods=safe", "--ws-external", "--unsafe-rpc-external", "--prometheus-external", "--telemetry-url", "wss://telemetry.mvs.org/ws/submit 0", "--name", "rpc-archive-X", "--pruning=archive"]
networks:
    metaverse:
        driver: bridge
        ipam:
            config:
                - subnet: 172.30.0.0/16
  