apiVersion: apps/v1
kind: Deployment
metadata:
  name: metaversevm-bootnode
  namespace: metaversevm
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metaversevm-bootnode
    spec:
      containers:
        - image: fade2019/metaverse:v0.0.1
          imagePullPolicy: Always
          name: bootnode
          # command: ["/usr/local/bin/metaverse","--unsafe-rpc-external","--unsafe-ws-external","--chain=/tmp/chainspec.json","--port=30333","--ws-port=9944","--rpc-port=9933","--base-path=/tmp/chaindata","--no-mdns","--name=bootnode","--pruning=archive","--rpc-methods","Unsafe","--rpc-cors=all","-lsubstrate_basic_authorship=trace,txpool=trace"]
          # The command here does not use the chainspec.json file, if you need to use it, please use the above command
          command: ["/usr/local/bin/metaverse","--unsafe-rpc-external","--name","bootnode","--validator","--rpc-cors","all","--base-path","/tmp/bootnode","--node-key","0000000000000000000000000000000000000000000000000000000000000111"]
          volumeMounts:
            - mountPath: /tmp/chainspec.json
              name: bootnode-spec
          ports:
            - containerPort: 30333
              name: p2p
            - containerPort: 9944
              name: ws
            - containerPort: 9933
              name: rpc
            - containerPort: 9615
              name: promethus
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 30
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
          readinessProbe:
            tcpSocket:
              port: 9933
            failureThreshold: 3
            periodSeconds: 5
            successThreshold: 3
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 9933
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
      terminationGracePeriodSeconds: 30
      volumes:
        - name: bootnode-spec
          hostPath:
            path: {BASE_DIR}/new-frontiers/docker/aura-grandpa/data/bootnode-spec.json
            type: FileOrCreate
  selector:
    matchLabels:
      app: metaversevm-bootnode
