apiVersion: apps/v1
kind: Deployment
metadata:
  name: metaversevm-validator
  namespace: metaversevm
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metaversevm-validator
    spec:
      containers:
        - image: fade2019/metaverse:v0.0.1
          imagePullPolicy: Always
          name: validator
          # command: ["/usr/local/bin/metaverse","--unsafe-rpc-external","--unsafe-ws-external","--chain=/tmp/chainspec.json","--rpc-methods","Unsafe","--rpc-cors=all","--base-path=/tmp/chaindata","--no-mdns","--validator","/ip4/metaversevm-bootnode/tcp/30333/p2p/12D3KooWRBaMZHnFYtT1B143sSLHkx8G6ysPSg8PMzqXkymm38Ld"]
          # The command here does not use the chainspec.json file, if you need to use it, please use the above command
          # It is important to note that the ip of the "--bootnodes" parameter needs to be changed to the clusterIP of the actual boot-node
          command: ["/usr/local/bin/metaverse","--unsafe-rpc-external","--name","bootnode","--validator","--rpc-cors","all","--base-path","/tmp/bootnode","--bootnodes","/ip4/10.109.17.74/tcp/30333/p2p/12D3KooWRBaMZHnFYtT1B143sSLHkx8G6ysPSg8PMzqXkymm38Ld"]
          volumeMounts:
            - mountPath: /tmp/chainspec.json
              name: validator-spec
          ports:
            - containerPort: 30333
              name: p2p
            - containerPort: 9944
              name: ws
            - containerPort: 9933
              name: rpc
            - containerPort: 9615
              name: promethus
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 30
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
          readinessProbe:
            tcpSocket:
              port: 9933
            failureThreshold: 3
            periodSeconds: 5
            successThreshold: 3
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 9933
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
      terminationGracePeriodSeconds: 30
      volumes:
        - name: validator-spec
          hostPath:
            path: {BASE_DIR}/new-frontiers/docker/aura-grandpa/data/validator-spec.json
            type: FileOrCreate
  selector:
    matchLabels:
      app: metaversevm-validator
