[package]
name = "metaverse"
version = "3.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Metaverse"
edition = "2018"
license = "Unlicense"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/mvs-org/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.4"
log = "0.4.8"
structopt = "0.3.8"
jsonrpc-core = "15.0.0"
jsonrpc-pubsub = "15.0.0"
hex-literal = "0.3.1"
sp-api = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sp-blockchain = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sc-rpc-api = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sc-rpc = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
substrate-frame-rpc-system = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
pallet-transaction-payment-rpc = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sc-cli = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sp-core = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sc-executor = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sc-service = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sp-inherents = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sc-transaction-pool = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sp-transaction-pool = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sc-network = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sc-consensus-aura = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sp-consensus-aura = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sc-consensus-manual-seal = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sp-consensus = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sc-consensus = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sp-timestamp = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
pallet-evm = { path = "../../frame/evm" }
pallet-ethereum = { path = "../../frame/ethereum" }
sc-finality-grandpa = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sp-finality-grandpa = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sc-client-api = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sp-runtime = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sc-basic-authorship = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sp-block-builder = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }
sc-telemetry = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }

fc-consensus = { path = "../../client/consensus" }
fp-consensus = { path = "../../primitives/consensus" }
metaverse-runtime = { path = "../runtime", default-features = false, features = ["std"] }
fc-rpc = { path = "../../client/rpc" }
fp-rpc = { path = "../../primitives/rpc" }
array-bytes = { path = "../../primitives/array-bytes" }
fc-rpc-core = { path = "../../client/rpc-core" }
fc-db = { path = "../../client/db" }
fc-mapping-sync = { path = "../../client/mapping-sync" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/mvs-org/substrate.git", branch = "master" }

[features]
default = ["aura"]
aura = ["metaverse-runtime/aura"]
manual-seal = ["metaverse-runtime/manual-seal"]

